shell.executable("/bin/bash")
shell.prefix("source ~/.bash_profile; ")

""" Snakefile for running 10x pipeline """
# cellranger directory added to .bashrc 

configfile: "config.yaml"

DATA = config["DATA"]
RUN = config["RUN"]
TRANSCRIPTOME = config["TRANSCRIPTOME"]
SAMPLE_SHEET = config["SAMPLE_SHEET"]
PROJECT = config["PROJECT"]
LANES = config["LANES"]
SAMPLES = config["SAMPLES"]
#SAMPLES_OUT = [x[:-1] + x[-1] for x in SAMPLES]
INDICIES = config["INDICIES"]

rule all:
    input:
      expand("{data}/raw_data/Stats/DemultiplexingStats.xml",
      data=DATA),
      expand("{sample}/outs/cloupe.cloupe",
      sample = SAMPLES)

#def _rename_input(wildcards):
#    """ for some reason I need to rename the output 
#    something more unique, otherwise cellranger count will fail...
#    This function takes the renamed output and pulls out the sampleid """
#    
#    sample = wildcards.sample
#    sample_number = sample[-1]
#    sample_id = sample[:-1]
#    return sample_id + sample_number

rule cellranger_count:
    input:
      "{data}/raw_data/Stats/DemultiplexingStats.xml".format(data=DATA)      
    output:
      "{sample}/outs/cloupe.cloupe"
    params:
      indir = "{data}/raw_data/{project}/".format(data = DATA, project = PROJECT),
      #sampleid  = _rename_input,
      lanes = LANES,
      job_name = "count",
      memory = "select[mem>4] rusage[mem=4]",
    log: "{data}/results/logs/count.out".format(data = DATA)
    threads: 2
    shell:
      """
      cellranger count \
          --id={wildcards.sample} \
          --fastqs={params.indir} \
          --sample={wildcards.sample} \
          --lanes={params.lanes} \
          --jobmode=lsf \
          --maxjobs=24 \
          --transcriptome={TRANSCRIPTOME}
      """ 

rule cellranger_mkfastq:
    input:
      SAMPLE_SHEET 
    output:
      "{data}/raw_data/Stats/DemultiplexingStats.xml"      
    params:
      outdir = "{data}/raw_data/",
      job_name = "count",
      memory = "select[mem>4] rusage[mem=4]",
    log: "{data}/results/logs/count.out"
    threads: 2
    shell:
      """
      module load bcl2fastq
      cellranger mkfastq \
          --run={RUN} \
          --samplesheet={SAMPLE_SHEET} \
          --project={PROJECT} \
          --jobmode=lsf \
          --maxjobs=24 \
          --output-dir {params.outdir} \
          --lanes {LANES} 
      module unload bcl2fastq
      """

